// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzvosfqledktvlsijnhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6dm9zZnFsZWRrdHZsc2lqbmhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NjEyODksImV4cCI6MjA1OTQzNzI4OX0.QibKxnUUtwJhg0o-kvHTm2PoOm7T7T7oFIEu7WUuLr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);